language: php

php:
  - 5.5
  - 5.4
  - 5.3
  
matrix:
  fast_finish: true
    
before_install:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_script:
  # Apache webserver configuration
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=3.5.0 SOLR_PORT=8080 SOLR_CONFS="3.x/schema.xml 3.x/schema_extra_fields.xml 3.x/schema_extra_types.xml 3.x/solrconfig.xml 3.x/elevate.xml 3.x/solrconfig_extra.xml 3.x/solrcore.properties 3.x/protwords.txt 3.x/mapping-ISOLatin1Accent.txt 3.x/synonyms.txt" bash
  #- curl https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=3.5.0 bash
  - sudo find / -name "conf" -type d -print
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql php5-curl
  - sudo sed -i -e "s,/var/www,$(pwd)/docroot,g" /etc/apache2/sites-available/default
  - sudo a2enmod rewrite
  - sudo a2enmod actions
  - sudo service apache2 restart
  # MySQL database configuration
  - mysql -e 'CREATE DATABASE devtrac;'
  # Ant build tool configuration
  - cp build.properties.dist build.properties
  - sed -i -e "s,username:password@host/db,travis@127.0.0.1/devtrac,g" build.properties
  #- cd build 
  #- drush --yes make build-devtrac.make build
  #- cp profiles/devtrac/modules/contrib/search_api_solr/solr-conf/3.x/* /home/travis/build/TddDoctor/devtrac/apache-solr-3.5.0/example/solr/conf/
script:
  - ant run-tests
  - TEST_EXIT=${PIPESTATUS[0]}
  #- TRAVIS_TEST_RESULT=$(! egrep -i "([0-9]+ fails)|(PHP Fatal error)|([0-9]+ exceptions)")$?
  - if [ $TEST_EXIT -eq 0 ]; then exit 0; else exit 1; fi
after_script:
  - echo TRAVIS_TEST_RESULT

notifications:
  irc:
    - "chat.freenode.net#devtrac"
